### ISSUE TITLE
a playback inaccuracy (handling Amiga periods as if they're linear)

### ISSUE THREAD

**Issue by RepellantMold** [sbechet/xmrsplayer#5]
I had noticed that some portamento slides were off during a fast section when I attempted to play one of my latest songs that was released in XM format called [Jaded Nostalgia](https://modarchive.org/module.php?203682) (the section in question is at 125 BPM / 2 tick speed).

The module with just the part and a lot of channels removed so you can focus on the lead
[fast_port.xm.zip](https://github.com/sbechet/xmrsplayer/files/14591391/fast_port.xm.zip)

Below are downloads to audio clips (since wave files are not uploadable :/)

[XMrsPlayer (latest main branch)](https://cdn.discordapp.com/attachments/408337336913494026/1217520722478497932/test_xmrsp.wav?ex=66045388&is=65f1de88&hm=a651788a657672602a29503aeebdf1fce44fc70c004ef24255526140f0b62a68&)

[OpenMPT 1.31.05.00](https://cdn.discordapp.com/attachments/408337336913494026/1217520722184900721/test_ompt.wav?ex=66045388&is=65f1de88&hm=647d2a54bae67c8da77481a1b3f37d5adea7abbcb28743c687c2cfa311b9700f&)

[MilkyTracker 1.04.00](https://cdn.discordapp.com/attachments/408337336913494026/1217520721698230392/test_milky.wav?ex=66045388&is=65f1de88&hm=ce33539c36ea6c32ab1e4fae305c06f7b8c5f457284d0d162bfbd4b1959d1a78&)

[FastTracker 2 Clone v1.77](https://cdn.discordapp.com/attachments/408337336913494026/1217520721257959425/test_ft2c.wav?ex=66045388&is=65f1de88&hm=a9831ee6de35c59907a5d822801249860f928eae1317016174e34bd5fc73175b&)

**Comment by sbechet** [comment]
Hello RepellantMold,

Thank you for your report. You right.

Over the next few days, I will finish creating the necessary abstractions to make the effects code more readable. Then, I plan to look in more detail at the algorithms in FT2-clone and I hope to be able to correct your problem quickly thanks to your example..

**Comment by sbechet** [comment]
Hello,

I found (an understand) the bug.

The effect parameter (and probably others) obviously applies to the octave A=440Hz. Which is not the case in the current code. I will make the changes as soon as possible.


# FastTracker II Clone

printf("period:%d->%d, speed:%d now:%d",ch->realPeriod, ch->wantPeriod, ch->portaSpeed, ch->realPeriod-ch->portaSpeed);

period:884->441, speed:16 now:868
period:868->441, speed:16 now:852
period:852->441, speed:16 now:836
period:836->441, speed:16 now:820

period:820->441, speed:32 now:788
period:788->441, speed:32 now:756
period:756->441, speed:32 now:724
period:724->441, speed:32 now:692

period:692->441, speed:252 now:440


# XMrsPlayer

print!("period:{}->{}, speed:{}", self.period, self.tone_portamento_target_period, self.tone_portamento_speed);
...
println!(" now:{}", self.period);

period:3873->3105, speed:16 now:3857
period:3857->3105, speed:16 now:3841
period:3841->3105, speed:16 now:3825
period:3825->3105, speed:16 now:3809

period:3809->3105, speed:32 now:3777
period:3777->3105, speed:32 now:3745
period:3745->3105, speed:32 now:3713
period:3713->3105, speed:32 now:3681

period:3681->3105, speed:252 now:3429

**Comment by sbechet** [comment]
Can you try again with xmrsplayer and xmrs in version 0.4.2 please :-)

**Comment by RepellantMold** [comment]
Testing it again with the version you suggested, and it now sounds correct.

**Comment by sbechet** [comment]
I reintroduced the bug :( your file is really a good test case.

**Comment by sbechet** [comment]
I don't understand the previous problem, but the auto-vib bug seems to be fixed in version 0.4.6

**Comment by sbechet** [comment]
I'm just discovering the [openMPT test cases](https://wiki.openmpt.org/Development:_Test_Cases/XM). I'll try to take a look at it in the next few months.

**Comment by RepellantMold** [comment]
> Hello,
> 
> I have a very strange things. I'm using ft2-clone for test.
> 
> [t2.zip](https://github.com/sbechet/xmrsplayer/files/14730976/t2.zip)
> 
> Here you find `t1_remove1and2.xm` where i simply remove track 1 and track 2: music sound seems correct with ft2 but bad with xmrsplayer.
> 
> Then i decide to save instrument 2 in `t1_2.xi` and track 3 in `t1.xt`. I create a new project in ft2 then load instr and track. Here you find the result: `t1_copy_past.xm`.
> 
> Now sound is the same using ft2 _and_ xmrsplayer. But music track is ugly for all.
> 
> Do you have an idea?

well my song doesn't use linear slides, and `t1_copy_past.xm` has linear slides turned on

**Comment by sbechet** [comment]
> > Do you have an idea?
> 
> well my song doesn't use linear slides (something I admit I should've brought up first), and `t1_copy_past.xm` has linear slides turned on

oops second time with the same problem! I changed a lot of things to have more abstraction and less bug in v0.4.7.

I'm going to take a little break because making an accurate player is, I think, absolutely impossible to succeed nor is this the objective of this project..

However, I think I have a not too bad result now. I'll have to motivate myself to make a little editor around the player now then include new "instruments" like i want in xmrs (SID Instr, Rob Hubbard Instr, Euclidian Rythms Instr and midi).
